### ISSUE TITLE
npm package seems to be broken

### ISSUE THREAD

**Issue by alexzurbonsen** [Green-Software-Foundation/if-unofficial-plugins#42]
I would expect that following the Readme and running

```
npm i -g @grnsft/if
npm i -g @grnsft/if-unofficial-models
```

and the following manifest file below (from co2js readme) with

`impact-engine --impl path/to/manifest`

should work. But it does run into an error:

`... Co2jsModel is not constructable or does not belong to given plugin ....`

The manifest file:
```
name: co2js-demo
description: example impl invoking CO2.JS model
tags:
initialize:
  models:
    - name: co2js
      model: Co2jsModel
      path: '@grnsft/if-unofficial-models'
graph:
  children:
    child:
      pipeline:
        - co2js
      config:
        co2js:
          type: swd
      inputs:
        - timestamp: 2023-07-06T00:00 # [KEYWORD] [NO-SUBFIELDS] time when measurement occurred
          duration: 1
          bytes: 1000000
          green-web-host: true
          options:
            dataReloadRatio: 0.6,
            firstVisitPercentage: 0.9,
            returnVisitPercentage: 0.1,
            gridIntensity:
              device: 560.98
              dataCenter:
                country: 'TWN'
```

It is not broken on `main` though. If I
- clone the `if-unofficial-models` repo
- `npm install`
- `npm link`
- clone the `if` repo
- `npm install`
- `npm link @grnsft/if-unofficial-models`

and run the manifest via `npm run impact-engine -- --impl path/to/manifest` it works.

**Comment by jmcook1186** [comment]
This should be fixed with the latest release - please ping us if you keep having issues.
