### ISSUE TITLE
Wattime Plugin Error

### ISSUE THREAD

**Issue by anthonyli633** [Green-Software-Foundation/if-unofficial-plugins#66]
When running the wartime plugin using the code provided in the README, I obtain the following error:

```
error:     WattTimeAPI: Error fetching data from WattTime API. "Invalid scope. You do not have sufficient access to this resource. See https://https//watttime.org/docs-dev/data-plans/ for more information or email contact@watttime.org for pricing. Please note that all users are allowed free access to CAISO_NORTH.".
APIRequestError:        WattTimeAPI: Error fetching data from WattTime API. "Invalid scope. You do not have sufficient access to this resource. See https://https//watttime.org/docs-dev/data-plans/ for more information or email contact@watttime.org for pricing. Please note that all users are allowed free access to CAISO_NORTH.".
```

Is there any way to fix this problem because other plugins work fine?

**Comment by manushak** [comment]
Hi @anthonyli633, thank you for opening a ticket. We will update the manifest so that all users can run it with free plan credentials. In the meantime, you can try using this manifest:

`name: watt-time-demo
description: null
tags: null
initialize:
  plugins:
    mock-observations:
      path: "@grnsft/if-plugins"
      method: MockObservations
      global-config:
        timestamp-from: "2024-03-05T00:00:00.000Z"
        timestamp-to: "2024-03-05T00:10:00.000Z"
        duration: 60
        components:
          - cloud/instance-type: Standard_E64_v3
          - cloud/instance-type: Standard_E64_v4
        generators:
          common:
            cloud/vendor: azure
            cloud/region: westus
            cloud/region-wt-id: CAISO_NORTH
          randint:
            cpu/utilization:
              min: 1
              max: 99
    watttime:
      path: "@grnsft/if-unofficial-plugins"
      method: WattTimeGridEmissions
tree:
  children:
    application:
      pipeline:
        - mock-observations
        - watttime
      config:
      inputs:`

**Comment by jmcook1186** [comment]
Closing as complete
